services:
   db:
      container_name: annapostgres
      image: postgres:alpine
      environment:
        POSTGRES_USER: amigoscode
        POSTGRES_PASSWORD: password
        PGDATA: /data/postgres
      volumes:
        - db:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - db
      restart: unless-stopped

networks:
   db:
      driver: bridge
volumes:
   db:
